### PR TITLE
feat(AdditionalFilters): Unique Filter

### LINKED ISSUE #5: Remove characters from pool option and/or option to generate more than one team.
Hey, thanks for the awesome work - this is looking to be a very practical tool! There is one feature that I would like to see that hasn't been listed in the current issues yet.
I like doing abyss randomizers and I like to reroll new teams for every floor without reusing characters. This can be achieved by either adding the option of having characters be removed from the pool after they have been rolled once or by rolling mutliple teams at once (here it can be an option if characters can appear in multiple teams or not).
Keep up the good work!

### PR DESCRIPTION
**Pull request by adnan007d**
When this filter is active deselects all the characters in the current team so that the new team won't include them

### CODE REVIEW

**Comment by Pustur** [comment]
Hey thanks for the interest shown for this feature.

The thing I don't like about this approach is that it changes the selected characters.

Originally the idea was that you only need to enter the characters that you own once, then every time you visit the page again they would still be there, saved locally.

With this feature you're gradually deselecting more and more characters so the next time you want to use it you'd have to reselect all the characters manually.

I think allowing to generate up to 8 teams (2 teams for each floor from 9 to 12) would be a better solution in this case.

Here's a possible mockup of how it could work, with a [+] button to add another row, and a [–] button to remove a row:

mockup

**Comment by adnan007d** [comment]
Makes sense, I will work on it

Should I keep the additional filters for future use or remove it?
I was also thinking of generating  full useable team (healer, support, dps)

**Comment by Pustur** [comment]
> Should I keep the additional filters for future use or remove it?

No you can remove it.

> I was also thinking of generating full useable team (healer, support, dps)

No that is too complex to implement but more importantly to support in the long term.  
There are too many variables that go into that. Some characters can change role depending on the build or with constellations. How much healing makes a character a healer? Can anybody with prototype amber be considered a healer? etc.

Let's just stick with the easy option of totally random teams.

(If you really want to add that feature you're free to host your own fork)

**Comment by adnan007d** [comment]
Hey, I did the changes have a look

**Comment by Pustur** [comment]
Update: I used your PR as a base but I changed a few things (for example the team size will be saved to local storage).

Due to the way that I worked I won't accept this PR directly, instead I have mentioned you as the co-author in my commit, I hope that's ok.

The feature will be released closer to the 4.4 patch.

**Comment by adnan007d** [comment]
Sure, no problem. We can close this PR then

**Pull request closed without merging**
